### PR TITLE
fuckjack: Support newer versions of jack-server

### PR DESCRIPTION
**Pull request by AgentFabulous**
- Android 8.0 appears to be using jack-server-4.11.ALPHA.jar
  and not jack-server-4.8.ALPHA.jar
- Use jack-server irrespective of subversion

Test: Jack server starts correctly

Signed-off-by: Kshitij Gupta <kshitijgm@gmail.com>

### CODE REVIEW

**Comment by mikecriggs** [comment]
This looks good, but I'd like to have the jar hard coded for Android 8.X. I'll make a new branch for Android 8.X. Would you be able to push this again to that branch when I make it? You can message me on Telegram at MikeCriggs and we can chat there. I don't often check this repo so I never respond in a timely manor here, haha.

**Comment by AgentFabulous** [comment]
Sure, I'll message you on telegram :)

**Comment by mikecriggs** [comment]
Please push this again to the "oreo" branch. Thank you :)

**Comment by mikecriggs** [comment]
Just make sure to hardcode the 4.11 jar

**Pull request closed without merging**
